### ISSUE TITLE
How to add a webhook for all issues and notifications ?

### ISSUE THREAD

**Issue by Paullux** [Slimefun/discord-webhook#18]
How to add a webhook for all issues and notifications ?

**Comment by TheBusyBiscuit** [comment]
You can find plenty of tutorials for that online.
I find this one particularly helpful: https://gist.github.com/jagrosh/5b1761213e33fc5b54ec7f6379034a22
You can also select the individual events, e.g. "issues".

Not sure why you are posting this here... but hope that helps you, if not just google "github discord webhook".
